<a href="https://colab.research.google.com/github/Jennifer-Arriola/Algoritmos/blob/main/Clases/Clase_9_Est_de_Datos_Lineales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algoritmos y Estructuras de Datos.

## - Clase 9 - Estructuras de Datos Lineales -

### Tipos de Datos Abstractos (TAD)


- Tipos de Datos
- Listas Enlazadas
- Pilas
- Colas

# Tipos de Estructuras Lineales

- Pilas
- Colas
- Listas Enlazadas

**Pros:**
- Dymanicas!

## Pilas

El comportamiento de una *Pila* se puede describir mediante la frase “Lo último que se apiló es lo primero que se usa”. Este método se llama **LIFO** (Last In First Out).

Formalmente un *Pila* es un TAD que tiene las siguientes operaciones:

- \_\_init\_\_ : Inicializa una pila vacía.

- push (apilar): Agrega un nuevo elemento a la Pila

- pop (desapilar): Remueve el *tope* de la Pila y lo devuelve. Este es el último elemento que se agregó.

- is\_empty (está\_vacía): Retorna **True** o **False** según si la pila está vacía o no.

Opcionles:

- top : Retorna el *tope* de la Pila (sin removerlo).


In [ ]:
p=Pila()

def top(P):
    if is_empty : pass
    x = P.pop
    P.push(x)
    return x


### Implementación de Pilas útilizando Listas

Definiremos una clase Pila con un atributo, items, de tipo lista, que contendrá los ele- mentos de la pila. El tope de la pila se encontrará en la última posición de la lista, y cada vez que se apile un nuevo elemento, se lo agregará al final.

In [ ]:
class Pila:
    """ Representa una pila con operaciones de apilar, desapilar y
        verificar si está vacía. """

    def __init__(self):
        """ Crea una pila vacía. """
# La pila vacía se representa con una lista vacía
        self.items=[]

    def push(self, x):
        """ Agrega el elemento x a la pila. """
# Apilar es agregar al final de la lista.
        self.items.append(x)

# Desapilar usará el método pop de lista que hace exactamente lo requerido
    def pop(self):
        """ Devuelve el elemento tope y lo elimina de la pila.
            Si la pila está vacía levanta una excepción. """
        try:
            return self.items.pop()
        except IndexError:
            raise ValueError("La pila está vacía")

# El método para indicar si se trata de una pila vacía.
    def is_empty(self):
        """ Devuelve True si la lista está vacía, False si no. """
        return self.items == []



In [ ]:
p = Pila()
p.is_empty()
p.push(1)
p.is_empty()
p.push(5)
p.push("+")
p.push(23)
p.pop()


23

Ejercicio: Implementar el método **top**, modificando el método **pop**.  

In [ ]:
#Ejercicio: Implementar el método **top**, modificando el método **pop**.


# Retorna el *tope* de la Pila
## Modificar ##
def pop(self):
    """ Devuelve el elemento tope y lo elimina de la pila.
    Si la pila está vacía levanta una excepción. """
    try:
        return self.items.pop()
    except IndexError:
        raise ValueError("La pila está vacía")

def top(self): # , P):
    if is_empty : pass
    x = self.items.pop() # x = P.pop #
    self.items.append(x)# P.push(x) #
    return x



## Colas


Todos sabemos lo que es una *Cola*. Este método se llama **FIFO** (First In First Out).

Formalmente un *Cola* es un TAD que tiene las siguientes operaciones:

- \_\_init\_\_ : Inicializa una cola vacía.

- enqueue (encolar o push): Agrega un nuevo elemento al final de la Cola

- dequeue (desencolar o pop): Remueve el primer elemento de la Cola y lo devuelve.

- is\_empty (está\_vacía): Retorna **True** o **False** según si la Cola está vacía o no.



In [ ]:
class Cola:
    """ Representa a una cola, con operaciones de encolar y
    desencolar. El primero en ser encolado es también el primero en ser desencolado. """

    def __init__(self):
        """ Crea una cola vacía. """
# La cola vacía se representa por una lista vacía
        self.items = []


#El método encolar se implementará agregando el nuevo elemento al final de la lista:
    def encolar(self, x):
        """ Agrega el elemento x como último de la cola. """
        self.items.append(x)

    def desencolar(self):
        """ Elimina el primer elemento de la cola y devuelve su
        valor. Si la cola está vacía, levanta ValueError. """
        try:
            return self.items.pop(0)
        except:
            raise ValueError("La cola está vacía")

#Por último, el método es_vacia, que indicará si la cola está o no vacía.
    def es_vacia(self):
        """ Devuelve True si la cola esta vacía, False si no."""
        return self.items == []


In [ ]:
q = Cola()
q.es_vacia()
q.encolar(1)
q.encolar("hola")
q.encolar(5)
q.es_vacia()
q.desencolar()
#q.desencolar()
q.encolar(8)
q.desencolar()
q.desencolar()
q.es_vacia()
#q.desencolar()

False

# Listas, Pilas y Colas Enlazadas

## Listas enlazadas

### Nodos

Crearemos un nuevo objeto **Nodo**, este será el bloque constructor de nuestras estructuras de datos lineales.

In [ ]:
class Nodo(object):
    def __init__(self, dato=None, prox = None):
        self.dato = dato
        self.prox = prox
    def __str__(self):
        return str(self.dato)




### Operaciones

Definimos a continuación las operaciones que inicialmente deberá cumplir la clase ListaEnlazada.

- \_\_str\_\_, para mostrar la lista.

- \_\_len\_\_, para calcular la longitud de la lista.

- append(x), para agregar un elemento al final de la lista.

- insert(i, x),paraagregarelelementoxenlaposicióni(levantaunaexcepciónsila posición i es inválida).

- remove(x), para eliminar la primera aparición de x en la lista (levanta una excepción si x no está).

- pop([i]), para borrar el elemento que está en la posición i y devolver su valor. Si no se especifica el valor de i,

- pop() elimina y devuelve el elemento que está en el último lugar de la lista (levanta una excepción si se hace  referencia a una posición no válida de la lista).

- index(x), devuelve la posición de la primera aparición de x en la lista (levanta una excepción si x no está).


![Screenshot%202021-09-14%20at%2023.13.40.png](attachment:Screenshot%202021-09-14%20at%2023.13.40.png)

Definicion de la clase Nodo:

In [ ]:
class ListaEnlazada(object):
    " Modela una lista enlazada, compuesta de Nodos. "
    def __init__(self):
        """ Crea una lista enlazada vacía. """
    # prim: apuntará al primer nodo - None con la lista vacía
        self.prim = None
    # len: longitud de la lista - 0 con la lista vacía
        self.len = 0


# Definicion de los métodos mas importantes:

In [ ]:
class ListaEnlazada(object):
    " Modela una lista enlazada, compuesta de Nodos. "
    def __init__(self):
        """ Crea una lista enlazada vacía. """
    # prim: apuntará al primer nodo - None con la lista vacía
        self.prim = None
    # len: longitud de la lista - 0 con la lista vacía
        self.len = 0



    def pop(self, i = None):
        """ Elimina el nodo de la posición i, y devuelve el dato contenido.
            Si i está fuera de rango, se levanta la excepción IndexError. Si no se recibe la posición, devuelve el último elemento. """
    # Si no se recibió i, se devuelve el último.
        if i is None:
            i = self.len - 1
     # Verificación de los límites
            if not (0 <= i < self.len):
                raise IndexError("Índice fuera de rango")
# Caso particular, si es el primero,
# hay que saltear la cabecera de la lista
        if i==0:
            dato = self.prim.dato
            self.prim = self.prim.prox
     # Para todos los demás elementos, busca la posición
        else:
            n_ant = self.prim
            n_act = n_ant.prox
        for pos in range(1, i):
            n_ant = n_act
            n_act = n_ant.prox
         # Guarda el dato y elimina el nodo a borrar
            dato = n_act.dato
            n_ant.prox = n_act.prox
     # hay que restar 1 de len
            self.len -= 1
     # y devolver el valor borrado
        return dato

In [ ]:
def remove(self, x):
    """ Borra la primera aparición del valor x en la lista.
        Si x no está en la lista, levanta ValueError """
    if self.len == 0:
    # Si la lista está vacía, no hay nada que borrar.
        raise ValueError("Lista vacía")
    # Caso particular, x esta en el primer nodo
    elif self.prim.dato == x:
    # Se descarta la cabecera de la lista
        self.prim = self.prim.prox
    # En cualquier otro caso, hay que buscar a x
    else:
    # Obtiene el nodo anterior al que contiene a x (n_ant) n_ant = self.prim
        n_act = n_ant.prox
        while n_act != None and n_act.dato != x:
            n_ant = n_act
            n_act = n_ant.prox
        # Si no se encontró a x en la lista, levanta la excepción
    if n_act == None:
        raise ValueError("El valor no está en la lista.")
# Si encontró a x, debe pasar de n_ant -> n_x -> n_x.prox # a n_ant -> n_x.prox
    else:
        n_ant.prox = n_act.prox
    # Si no levantó excepción, hay que restar 1 del largo
        self.len -= 1

In [ ]:
def insert(self, i, x):
    """ Inserta el elemento x en la posición i.
        Si la posición es inválida, levanta IndexError """
    if (i > self.len) or (i < 0): # error
        raise IndexError("Posición inválida") # Crea nuevo nodo, con x como dato:
    nuevo = _Nodo(x)
    # Insertar al principio (caso particular)
    if i==0:
# el siguiente del nuevo pasa a ser el que era primero
        nuevo.prox = self.prim
# el nuevo pasa a ser el primero de la lista
        self.prim = nuevo
    # Insertar en cualquier lugar > 0
    else:
# Recorre la lista hasta llegar a la posición deseada n_ant = self.prim
        for pos in range(1,i):
            n_ant = n_ant.prox
# Intercala nuevo y obtiene n_ant -> nuevo -> n_ant.prox
            nuevo.prox = n_ant.prox
            n_ant.prox = nuevo
    # En cualquier caso, incrementar en 1 la longitud
    self.len += 1

# Iteradores

Todas las secuencias pueden ser recorridas mediante una misma estructura ($\texttt{for variable in secuencia}$), ya que todas implementan el método especial **\_\_iter\_\_**. Este método debe devolver un **iterador** capaz de recorrer la secuencia como corresponda.


En particular, en Python, los iteradores tienen que implementar un método **\_\_next\_\_** que debe devolver los elementos, de a uno por vez, comenzando por el primero. Y al llegar al final de la estructura, debe levantar una excepción de tipo **StopIteration**.

Métodos requeridos:

- **\_\_iter\_\_**: Crea un objeto "Iterador".

- **\_\_next\_\_**: Siguiente elemento en la secuencia.

Excepciones:

- **StopIteration**: Nos avisa cuando se a llegador al final de la secuencia.


Es decir que las siguientes estructuras son equivalentes:

In [ ]:
for elemento in secuencia:
    # hacer algo con elemento


In [ ]:
iterador = iter(secuencia)
while True:
    try:
        elemento = iterador.next()
    except StopIteration:
        break
    # hacer algo con elemento

Queremos implementar un iterador para la *Lista Enlazada*, la mejor solución implica crear una nueva clase, *\_IteradorListaEnlazada*, que implemente el método *\_\_next()\_\_* de la forma apropiada.

In [ ]:
class _IteradorListaEnlazada(object):
    " Iterador para la clase ListaEnlazada "

    def __init__(self, prim):
        """ Constructor del iterador.
            prim es el primer elemento de la lista. """
        self.actual = prim

    def __next__(self):
        """ Devuelve uno a uno los elementos de la lista. """
        if self.actual == None:
            raise StopIteration("No hay más elementos en la lista")
        # Guarda el dato
        dato = self.actual.dato
        # Avanza en la lista
        self.actual = self.actual.prox
        # Devuelve el dato
        return dato



In [ ]:
def __iter__(self):
    " Devuelve el iterador de la lista. "
    return _IteradorListaEnlazada(self.prim)


In [ ]:
l = ListaEnlazada()
l.insert(0,1)
l.insert(0,2)
l.insert(0,3)
for valor in l:
    print(valor)

3
2
1


**Ejercicio:** Escribir los métodos **\_\_iter\_\_**, **\_\_str\_\_** y **\_\_len\_\_** para la lista.

# $~$

### Módulo numpy

Su Documentación completa está disponible aqui: http://www.numpy.org. Particularmente interesante para problemas mathematicos.
Nos ofrece un nuevo tipo de dato "arreglo" (array), tambien llamados "vectores", cuando todos los elementos son del mismo tipo.  


In [ ]:
import numpy as np

In [ ]:
v=np.array([[1,1,1,1]])# Crea un arreglo de 2 x 2 (es decir, una matríz).
                         # v= [ 1 | 1
                         #      1 | 1 ]
print(v)

print([[1,1,1,1]])

type(v)



[[1 1]
 [1 1]]
[[1, 1], [1, 1]]


numpy.ndarray

In [ ]:
v+=v
print(v)

[[2 2]
 [2 2]]


In [ ]:
v=np.array([[1,2],[3,4]])
print(v)
print(v[0][1]) # Podemos indexar los elementos de un array
v[0][1]=5
print(v)
w = v     # Los arrays son objetos "mutables".
w[0][1]=3
print(w,'\n',v)

[[1 2]
 [3 4]]
2
[[1 5]
 [3 4]]
[[1 3]
 [3 4]] 
 [[1 3]
 [3 4]]


In [ ]:
np.array([[True,2.0],[0+1j,0.1],(3+7*1j,-np.pi)]) # La *función* array normalizara los datos
                                                  # que ingresamos por parametros.

Además tenemos provisto el tipo $\textit{Matríz}$.

In [ ]:
M=np.matrix([[0,1j],[1j,0]]) # Tipo : matrix
print(M.conjugate()) # Retorna wl conjugado de la matríz.
print(M*M)